import { Copy, Eye, MoreHorizontal, Pencil, Trash2 } from 'lucide-react';
import JobStatusBadge from './JobStatusBadge';

const formatDate = (value) => {
  const date = value ? new Date(`${value}T00:00:00`) : null;
  return date && !Number.isNaN(date.getTime()) ? new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: '2-digit' }).format(date) : '—';
};

const JobTable = ({ jobs, applicantCounts, onView, onEdit, onDelete, onCopy, onDuplicate, onStatusChange }) => (
  <div className="max-w-full overflow-x-auto rounded-2xl border border-white/10 bg-slate-900/70">
    <table className="w-full min-w-[1120px] text-left text-sm">
      <thead className="border-b border-white/10 bg-slate-950/40 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3 font-medium">Job</th><th className="px-4 py-3 font-medium">Department</th><th className="px-4 py-3 font-medium">Location</th><th className="px-4 py-3 font-medium">Type</th><th className="px-4 py-3 text-center font-medium">Applicants</th><th className="px-4 py-3 text-center font-medium">Openings</th><th className="px-4 py-3 text-center font-medium">Match threshold</th><th className="px-4 py-3 font-medium">Deadline</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 text-right font-medium">Actions</th></tr></thead>
      <tbody className="divide-y divide-white/[0.07]">{jobs.map((job) => <tr key={job.id} className="transition hover:bg-white/[0.025]"><td className="max-w-56 px-4 py-4"><button type="button" onClick={() => onView(job)} className="block max-w-full truncate font-medium text-white hover:text-cyan-300">{job.title || 'Untitled job'}</button><p className="mt-0.5 truncate text-xs text-slate-600">{job.experienceRequired || 'Experience not specified'}</p></td><td className="px-4 py-4 text-slate-400">{job.department || '—'}</td><td className="px-4 py-4 text-slate-400">{job.location || '—'}</td><td className="px-4 py-4 text-slate-400">{job.employmentType || '—'}</td><td className="px-4 py-4 text-center font-medium text-slate-200">{applicantCounts[job.id] || 0}</td><td className="px-4 py-4 text-center text-slate-400">{job.openings || 0}</td><td className="px-4 py-4 text-center text-slate-400">{Number(job.minimumMatchScore) || 0}%</td><td className="px-4 py-4 text-slate-400">{formatDate(job.deadline)}</td><td className="px-4 py-4"><JobStatusBadge status={job.status} /></td><td className="px-4 py-4"><div className="flex items-center justify-end gap-1"><button type="button" onClick={() => onView(job)} className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-white/5 hover:text-cyan-300" aria-label={`View ${job.title}`}><Eye size={14} /></button><button type="button" onClick={() => onEdit(job)} className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-white/5 hover:text-white" aria-label={`Edit ${job.title}`}><Pencil size={14} /></button><button type="button" onClick={() => onCopy(job)} className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-white/5 hover:text-white" aria-label={`Copy ${job.title}`}><Copy size={14} /></button><button type="button" onClick={() => onDuplicate(job)} className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-white/5 hover:text-white" aria-label={`Duplicate ${job.title}`}><MoreHorizontal size={15} /></button><button type="button" onClick={() => onStatusChange(job, job.status === 'Open' ? 'Closed' : 'Open')} className="rounded-lg px-2 py-1.5 text-xs text-slate-500 hover:bg-white/5 hover:text-white">{job.status === 'Open' ? 'Close' : 'Open'}</button><button type="button" onClick={() => onDelete(job)} className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-rose-500/10 hover:text-rose-300" aria-label={`Delete ${job.title}`}><Trash2 size={14} /></button></div></td></tr>)}</tbody>
    </table>
  </div>
);

export default JobTable;
