import { createElement } from 'react';
import { Copy, Download, Eye, Pencil, Trash2 } from 'lucide-react';
import CandidateStatusBadge from './CandidateStatusBadge';
import MatchScoreBadge from './MatchScoreBadge';

const CandidateTable = ({ candidates, onView, onEdit, onDelete, onCopyEmail, onDownload }) => (
  <div className="max-w-full overflow-x-auto rounded-2xl border border-white/10 bg-slate-900/70"><table className="w-full min-w-[1150px] text-left text-sm"><thead className="border-b border-white/10 bg-slate-950/40 text-xs uppercase tracking-wider text-slate-500"><tr>{['Candidate', 'Applied job', 'Skills', 'Experience', 'Match score', 'AI recommendation', 'Status', 'Application date', 'Actions'].map((title) => <th key={title} className="px-4 py-3 font-medium">{title}</th>)}</tr></thead><tbody className="divide-y divide-white/[0.07]">{candidates.map((candidate) => <tr key={candidate.id} className="hover:bg-white/[0.025]"><td className="px-4 py-4"><button type="button" onClick={() => onView(candidate)} className="font-medium text-white hover:text-cyan-300">{candidate.name || 'Unknown'}</button><p className="text-xs text-slate-500">{candidate.email || 'No email'}</p></td><td className="max-w-48 px-4 py-4 text-slate-400">{candidate.appliedJob || 'Unassigned'}</td><td className="max-w-64 px-4 py-4"><div className="flex flex-wrap gap-1">{(candidate.skills || []).slice(0, 3).map((skill) => <span key={skill} className="rounded bg-white/5 px-1.5 py-0.5 text-[11px] text-slate-400">{skill}</span>)}</div></td><td className="px-4 py-4 text-slate-400">{Number(candidate.experienceYears) || 0} years</td><td className="px-4 py-4"><MatchScoreBadge score={candidate.matchScore} compact /></td><td className="px-4 py-4 text-slate-400">{candidate.aiRecommendation || 'Manual Review'}</td><td className="px-4 py-4"><CandidateStatusBadge status={candidate.status} /></td><td className="px-4 py-4 text-slate-400">{candidate.applicationDate || '—'}</td><td className="px-4 py-4"><div className="flex gap-1">{[[onView, Eye, 'View'], [onEdit, Pencil, 'Edit'], [onCopyEmail, Copy, 'Copy email'], [onDownload, Download, 'Download resume'], [onDelete, Trash2, 'Delete']].map(([handler, icon, label]) => <button key={label} type="button" onClick={() => handler(candidate)} className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-white/5 hover:text-white" aria-label={`${label} ${candidate.name}`}>{createElement(icon, { size: 14 })}</button>)}</div></td></tr>)}</tbody></table></div>
);
export default CandidateTable;
