import { useMemo, useState } from 'react';
import { Award, Eye } from 'lucide-react';
import MatchScoreBadge from './MatchScoreBadge';
import CandidateStatusBadge from './CandidateStatusBadge';

const CandidateRanking = ({ candidates, jobs, onView, onShortlist, onReject, onSelect }) => {
  const [jobId, setJobId] = useState(jobs[0]?.id || ''); const [score, setScore] = useState(''); const [experience, setExperience] = useState(''); const [skill, setSkill] = useState(''); const [status, setStatus] = useState('');
  const job = jobs.find((item) => item.id === jobId);
  const ranked = useMemo(() => candidates.filter((candidate) => candidate.appliedJobId === jobId && (!score || Number(candidate.matchScore) >= Number(score)) && (!experience || Number(candidate.experienceYears) >= Number(experience)) && (!skill || candidate.skills?.some((item) => item.toLowerCase().includes(skill.toLowerCase()))) && (!status || candidate.status === status)).sort((a, b) => Number(b.matchScore || 0) - Number(a.matchScore || 0)), [candidates, jobId, score, experience, skill, status]);
  return <section><div className="grid gap-3 rounded-2xl border border-white/10 bg-slate-900/60 p-4 sm:grid-cols-2 lg:grid-cols-5"><select value={jobId} onChange={(event) => setJobId(event.target.value)} className="rounded-xl bg-slate-950 p-2 text-sm text-white">{jobs.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input value={score} onChange={(event) => setScore(event.target.value)} type="number" placeholder="Minimum score" className="rounded-xl bg-slate-950 p-2 text-sm text-white" /><input value={experience} onChange={(event) => setExperience(event.target.value)} type="number" placeholder="Minimum experience" className="rounded-xl bg-slate-950 p-2 text-sm text-white" /><input value={skill} onChange={(event) => setSkill(event.target.value)} placeholder="Skill contains" className="rounded-xl bg-slate-950 p-2 text-sm text-white" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl bg-slate-950 p-2 text-sm text-white"><option value="">All statuses</option>{[...new Set(candidates.map((item) => item.status).filter(Boolean))].map((item) => <option key={item}>{item}</option>)}</select></div>
    {ranked.length ? <div className="mt-4 space-y-3">{ranked.map((candidate, index) => { const above = Number(candidate.matchScore) >= Number(job?.minimumMatchScore || 0); return <article key={candidate.id} className={`rounded-2xl border p-4 ${above ? 'border-emerald-500/25 bg-emerald-500/[0.03]' : 'border-white/10 bg-slate-900/70'}`}><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-500/10 font-semibold text-amber-300"><Award size={16} />{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-white">{candidate.name}</h3><CandidateStatusBadge status={candidate.status} />{above && <span className="text-xs text-emerald-300">Above threshold</span>}</div><p className="mt-1 text-xs text-emerald-400">Matched: {candidate.matchedSkills?.join(', ') || 'None'}</p><p className="text-xs text-amber-400">Missing: {candidate.missingSkills?.join(', ') || 'None'}</p></div><div className="grid grid-cols-4 gap-2 text-center text-xs text-slate-500"><span>Skill<b className="block text-slate-200">{candidate.skillScore || 0}</b></span><span>Exp<b className="block text-slate-200">{candidate.experienceScore || 0}</b></span><span>Edu<b className="block text-slate-200">{candidate.educationScore || 0}</b></span><span>Project<b className="block text-slate-200">{candidate.projectScore || 0}</b></span></div><MatchScoreBadge score={candidate.matchScore} /><div className="flex gap-1"><button onClick={() => onView(candidate)} aria-label="View candidate"><Eye size={16} /></button><button onClick={() => onShortlist(candidate)} className="rounded-lg px-2 py-1 text-xs text-violet-300">Shortlist</button><button onClick={() => onReject(candidate)} className="rounded-lg px-2 py-1 text-xs text-rose-300">Reject</button><button onClick={() => onSelect(candidate)} className="rounded-lg px-2 py-1 text-xs text-emerald-300">Select</button></div></div><p className="mt-3 text-xs text-slate-500">{candidate.aiRecommendation || 'Manual Review'}</p></article>; })}</div> : <p className="grid min-h-56 place-items-center text-sm text-slate-500">No candidates for selected job or ranking filters</p>}
  </section>;
};
export default CandidateRanking;
