import { ChevronLeft, ChevronRight } from 'lucide-react';
import MatchScoreBadge from './MatchScoreBadge';

// eslint-disable-next-line react-refresh/only-export-components
export const pipelineStatuses = ['Applied', 'Screening', 'Shortlisted', 'Interview Scheduled', 'Interview Completed', 'Selected', 'Offer Sent', 'Hired', 'Rejected'];
const RecruitmentPipeline = ({ candidates, onMove, onView }) => {
  const move = (candidate, status) => { if (status === 'Rejected' && !window.confirm(`Move ${candidate.name} to Rejected?`)) return; onMove(candidate, status); };
  return <div className="max-w-full overflow-x-auto pb-3"><div className="flex min-w-max gap-3">{pipelineStatuses.map((status, stageIndex) => { const stageCandidates = candidates.filter((candidate) => candidate.status === status); return <section key={status} className="w-72 shrink-0 rounded-2xl border border-white/10 bg-slate-900/50" aria-labelledby={`stage-${stageIndex}`}><div className="flex items-center justify-between border-b border-white/10 p-3"><h2 id={`stage-${stageIndex}`} className="text-sm font-semibold text-white">{status}</h2><span className="rounded-full bg-white/5 px-2 text-xs text-slate-400">{stageCandidates.length}</span></div><div className="max-h-[65vh] space-y-2 overflow-y-auto p-2">{stageCandidates.map((candidate) => <article key={candidate.id} className="rounded-xl border border-white/[0.07] bg-slate-950/60 p-3"><button type="button" onClick={() => onView(candidate)} className="text-left"><p className="font-medium text-white">{candidate.name}</p><p className="truncate text-xs text-slate-500">{candidate.appliedJob || 'Unassigned'}</p></button><div className="mt-2 flex items-center justify-between"><MatchScoreBadge score={candidate.matchScore} compact /><span className="text-[11px] text-slate-600">{candidate.applicationDate || '—'}</span></div><select value={candidate.status} onChange={(event) => move(candidate, event.target.value)} aria-label={`Move ${candidate.name}`} className="mt-2 w-full rounded-lg bg-slate-900 px-2 py-1 text-xs text-slate-300">{pipelineStatuses.map((item) => <option key={item}>{item}</option>)}</select><div className="mt-2 flex justify-between"><button disabled={stageIndex === 0} onClick={() => move(candidate, pipelineStatuses[stageIndex - 1])} aria-label="Move to previous stage"><ChevronLeft size={15} /></button><button disabled={stageIndex === pipelineStatuses.length - 1} onClick={() => move(candidate, pipelineStatuses[stageIndex + 1])} aria-label="Move to next stage"><ChevronRight size={15} /></button></div></article>)}{!stageCandidates.length && <p className="py-8 text-center text-xs text-slate-600">No candidates</p>}</div></section>; })}</div></div>;
};
export default RecruitmentPipeline;
