import { createElement, lazy, Suspense, useMemo, useState } from 'react';
import { Bot, LayoutGrid, List, Play, Plus, ScrollText, Sparkles } from 'lucide-react';
import PageHeader from '../components/common/PageHeader';
import RouteLoader from '../components/common/RouteLoader';
import AutomationCard from '../components/automations/AutomationCard';
import AutomationTable from '../components/automations/AutomationTable';
import AutomationFilters from '../components/automations/AutomationFilters';
import AutomationFormModal from '../components/automations/AutomationFormModal';
import AutomationDetailsModal from '../components/automations/AutomationDetailsModal';
import AutomationRunModal from '../components/automations/AutomationRunModal';
import AutomationMetrics from '../components/automations/AutomationMetrics';
import DeleteAutomationModal from '../components/automations/DeleteAutomationModal';
import AutomationStatusBadge from '../components/automations/AutomationStatusBadge';
import { useRecruitment } from '../context/RecruitmentContext';
import { calculateAutomationMetrics } from '../services/automationService';
import { AUTOMATION_CATEGORIES, TRIGGER_TYPES, cloneTemplate } from '../utils/automationTemplates';

const AutomationLogs=lazy(()=>import('../components/automations/AutomationLogs'));
const AutomationTemplateGallery=lazy(()=>import('../components/automations/AutomationTemplateGallery'));
const initialFilters={search:'',status:'',category:'',trigger:'',sort:'recent'};
const views=[['cards',LayoutGrid,'Cards'],['table',List,'Table'],['history',ScrollText,'Run History'],['templates',Sparkles,'Templates']];
const stamp=(value)=>Number.isFinite(new Date(value).getTime())?new Date(value).getTime():0;
export default function AutomationPage(){
 const ctx=useRecruitment(); const {automations,candidates,jobs,interviews,automationRuns=[],loading,addAutomation,updateAutomation,deleteAutomation,toggleAutomation,resetAutomationStatistics,runAutomation,simulateAutomationTrigger}=ctx;
 const [view,setView]=useState('cards'),[filters,setFilters]=useState(initialFilters),[page,setPage]=useState(1),[form,setForm]=useState(null),[formOpen,setFormOpen]=useState(false),[details,setDetails]=useState(null),[runItem,setRunItem]=useState(null),[deleteItem,setDeleteItem]=useState(null),[logsFor,setLogsFor]=useState(null),[runDetails,setRunDetails]=useState(null);
 const metrics=useMemo(()=>calculateAutomationMetrics(automations,automationRuns),[automations,automationRuns]);
 const filtered=useMemo(()=>{const q=filters.search.toLowerCase();return automations.filter(x=>!q||`${x.name} ${x.description} ${x.triggerType} ${x.category} ${x.steps?.map(s=>s.actionType).join(' ')}`.toLowerCase().includes(q)).filter(x=>!filters.status||x.status===filters.status).filter(x=>!filters.category||x.category===filters.category).filter(x=>!filters.trigger||x.triggerType===filters.trigger).sort((a,b)=>{const ar=a.totalRuns?Math.round(a.successfulRuns/a.totalRuns*100):0,br=b.totalRuns?Math.round(b.successfulRuns/b.totalRuns*100):0;return filters.sort==='oldest'?stamp(a.lastRun)-stamp(b.lastRun):filters.sort==='success-high'?br-ar:filters.sort==='success-low'?ar-br:filters.sort==='runs'?b.totalRuns-a.totalRuns:filters.sort==='failures'?b.failedRuns-a.failedRuns:filters.sort==='name'?a.name.localeCompare(b.name):stamp(b.lastRun)-stamp(a.lastRun);});},[automations,filters]);
 const changeFilters=(next)=>{setFilters(typeof next==='function'?next(filters):next);setPage(1);}; const changeView=(next)=>{setView(next);setPage(1);};
 const size=view==='cards'?8:10,pages=Math.max(1,Math.ceil(filtered.length/size)),items=filtered.slice((page-1)*size,page*size),history=useMemo(()=>automationRuns.slice().sort((a,b)=>stamp(b.startedAt)-stamp(a.startedAt)),[automationRuns]);
 const action=(name,item)=>{if(name==='view')setDetails(item);if(name==='edit'){setForm(item);setFormOpen(true);}if(name==='duplicate'){setForm({...item,id:undefined,name:`${item.name} Copy`,status:'Draft',totalRuns:0,successfulRuns:0,failedRuns:0,lastRun:null});setFormOpen(true);}if(name==='toggle')toggleAutomation(item.id);if(name==='run')setRunItem(item);if(name==='logs'){setLogsFor(item.id);changeView('history');}if(name==='reset'&&confirm(`Reset counters for ${item.name}? Run history will be preserved.`))resetAutomationStatistics(item.id);if(name==='delete')setDeleteItem(item);};
 const cardActions=(item)=>Object.fromEntries(['view','edit','duplicate','toggle','run','logs','reset','delete'].map(x=>[x,()=>action(x,item)]));
 if(loading)return <div className="space-y-4">{[1,2,3].map(x=><div key={x} className="h-28 animate-pulse rounded-2xl bg-slate-900"/>)}</div>;
 return <div className="min-w-0 space-y-6"><PageHeader eyebrow="Automation Center" title="Scale every hiring motion" description="Build, test, and monitor reliable recruitment workflows." actions={<div className="flex flex-wrap gap-2"><button onClick={()=>{setForm(null);setFormOpen(true);}} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2 font-semibold text-slate-950"><Plus size={17}/>New automation</button><button onClick={()=>{const trigger=prompt(`Simulate trigger:\n${TRIGGER_TYPES.join(', ')}`,'Candidate Added');if(trigger)simulateAutomationTrigger(trigger);}} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2"><Play size={16}/>Simulate trigger</button></div>}/><AutomationMetrics metrics={metrics}/>
 <div className="flex flex-wrap gap-2" role="tablist">{views.map(([id,Icon,label])=><button key={id} onClick={()=>changeView(id)} role="tab" aria-selected={view===id} className={`inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm ${view===id?'bg-cyan-500 text-slate-950':'border border-white/10 text-slate-300'}`}>{createElement(Icon,{size:16})}{label}</button>)}</div>
 {(view==='cards'||view==='table')&&<><AutomationFilters filters={filters} setFilters={changeFilters} categories={AUTOMATION_CATEGORIES} triggers={TRIGGER_TYPES}/>{!items.length?<div className="rounded-2xl border border-dashed border-white/10 py-16 text-center"><Bot className="mx-auto text-slate-600"/><p className="mt-3 text-slate-400">No automations match the current filters.</p></div>:view==='cards'?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(item=><AutomationCard key={item.id} item={item} actions={cardActions(item)}/>)}</div>:<AutomationTable items={items} onAction={action}/>} {pages>1&&<div className="flex justify-center gap-2"><button disabled={page===1} onClick={()=>setPage(x=>x-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(x=>x+1)}>Next</button></div>}</>}
 {view==='templates'&&<Suspense fallback={<RouteLoader compact/>}><AutomationTemplateGallery onUse={tpl=>{setForm({...cloneTemplate(tpl),id:undefined,status:'Draft'});setFormOpen(true);}} onPreview={setDetails}/></Suspense>} {view==='history'&&<HistoryView history={history} logsFor={logsFor} onDetails={setRunDetails}/>} 
 <AutomationFormModal key={`${formOpen}-${form?.id||form?.name||'new'}`} open={formOpen} item={form} automations={automations} onClose={()=>setFormOpen(false)} onSave={data=>form?.id?updateAutomation(form.id,data):addAutomation(data)}/><AutomationDetailsModal item={details} onClose={()=>setDetails(null)} onRun={item=>{setDetails(null);setRunItem(item);}}/><AutomationRunModal automation={runItem} candidates={candidates} jobs={jobs} interviews={interviews} onClose={()=>setRunItem(null)} onRun={runAutomation}/><DeleteAutomationModal item={deleteItem} onClose={()=>setDeleteItem(null)} onConfirm={()=>{deleteAutomation(deleteItem.id);setDeleteItem(null);}}/><RunDetails run={runDetails} automations={automations} onClose={()=>setRunDetails(null)} onRetry={item=>{setRunDetails(null);setRunItem(item);}}/></div>;
}
function HistoryView({history,logsFor,onDetails}){return <div className="space-y-4"><div className="overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-900 text-slate-400"><tr>{['Run ID','Automation','Trigger','Entity','Started','Duration','Status','Steps','Saved','Details'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{history.map(run=><tr key={run.id} className="border-t border-white/10 bg-slate-900/60"><td className="px-4 py-3 font-mono text-xs text-cyan-300">{run.id}</td><td className="px-4 py-3 text-white">{run.automationName}</td><td className="px-4 py-3">{run.trigger}</td><td className="px-4 py-3">{run.entityType||'—'} {run.entityId||''}</td><td className="px-4 py-3">{new Date(run.startedAt).toLocaleString('en-IN')}</td><td className="px-4 py-3">{Math.round((run.duration||0)/1000)}s</td><td className="px-4 py-3"><AutomationStatusBadge status={run.status}/></td><td className="px-4 py-3">{run.completedSteps?.length||0}</td><td className="px-4 py-3">{run.timeSaved||0}m</td><td className="px-4 py-3"><button onClick={()=>onDetails(run)} className="text-cyan-300">View</button></td></tr>)}</tbody></table>{!history.length&&<p className="py-12 text-center text-slate-500">No persisted runs yet.</p>}</div><Suspense fallback={<RouteLoader compact/>}><AutomationLogs runs={history} automationId={logsFor}/></Suspense></div>}
function RunDetails({run,automations,onClose,onRetry}){if(!run)return null;const item=automations.find(x=>x.id===run.automationId);return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-white/10 bg-slate-900 p-5"><h2 className="text-xl font-semibold text-white">Run {run.id}</h2><p className="mt-2 text-sm text-slate-400">{run.automationName} · {run.status}</p>{run.errorMessage&&<p className="mt-3 text-rose-300">{run.errorMessage}</p>}<ol className="mt-4 space-y-2">{run.logs?.map(log=><li key={log.id} className="rounded-xl bg-slate-950 p-3 text-sm"><span className="text-cyan-300">{log.severity}</span> · {log.message}</li>)}</ol><div className="mt-5 flex justify-end gap-2"><button onClick={onClose}>Close</button>{item&&<button onClick={()=>onRetry(item)} className="rounded-xl bg-cyan-500 px-4 py-2 text-slate-950">Retry</button>}</div></div></div>}
