import { createElement, useMemo, useState } from 'react';
import { ArrowLeft, CalendarPlus, Mail, MapPin, Pencil, Phone, Trash2 } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import AddCandidateModal from '../components/candidates/AddCandidateModal';
import CandidateStatusBadge from '../components/candidates/CandidateStatusBadge';
import CandidateTimeline from '../components/candidates/CandidateTimeline';
import DeleteCandidateModal from '../components/candidates/DeleteCandidateModal';
import MatchScoreBadge from '../components/candidates/MatchScoreBadge';
import RecruiterNotes from '../components/candidates/RecruiterNotes';
import PageHeader from '../components/common/PageHeader';
import { useRecruitment } from '../context/RecruitmentContext';

const CandidateDetailsPage = () => {
  const { candidateId } = useParams(); const navigate = useNavigate();
  const { candidates, jobs, interviews, activities, loading, updateCandidate, deleteCandidate, shortlistCandidate, rejectCandidate, selectCandidate } = useRecruitment();
  const [editOpen, setEditOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false);
  const candidate = candidates.find((item) => item.id === candidateId); const job = jobs.find((item) => item.id === candidate?.appliedJobId);
  const history = useMemo(() => interviews.filter((item) => item.candidateId === candidateId).sort((a, b) => `${b.date || ''}${b.time || ''}`.localeCompare(`${a.date || ''}${a.time || ''}`)), [interviews, candidateId]);
  if (loading) return <div className="h-96 animate-pulse rounded-3xl bg-slate-900/70" />;
  if (!candidate) return <div className="grid min-h-[60vh] place-items-center text-center"><div><h1 className="text-2xl font-semibold text-white">Candidate not found</h1><p className="mt-2 text-sm text-slate-500">The candidate may have been removed or the link is invalid.</p><button type="button" onClick={() => navigate('/candidates')} className="mt-5 rounded-xl bg-cyan-500 px-4 py-2 text-sm font-semibold text-slate-950">Back to candidates</button></div></div>;
  const scores = [['Overall', candidate.matchScore], ['Skills', candidate.skillScore], ['Experience', candidate.experienceScore], ['Education', candidate.educationScore], ['Projects', candidate.projectScore]];
  const remove = (force) => { if (deleteCandidate(candidate.id, { force })) navigate('/candidates'); };
  return <div className="min-w-0 space-y-6"><button type="button" onClick={() => navigate('/candidates')} className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-white"><ArrowLeft size={16} />Back to candidates</button><PageHeader eyebrow={candidate.appliedJob || 'Candidate profile'} title={candidate.name} description={candidate.summary || candidate.aiRecommendation || 'AI-assisted candidate profile'} actions={<div className="flex flex-wrap items-center gap-2"><CandidateStatusBadge status={candidate.status} /><MatchScoreBadge score={candidate.matchScore} compact /><button type="button" onClick={() => setEditOpen(true)} className="rounded-xl border border-white/10 p-2 text-slate-300" aria-label="Edit candidate"><Pencil size={16} /></button><button type="button" onClick={() => shortlistCandidate(candidate.id)} className="rounded-xl px-3 py-2 text-sm text-violet-300">Shortlist</button><button type="button" onClick={() => rejectCandidate(candidate.id)} className="rounded-xl px-3 py-2 text-sm text-rose-300">Reject</button><button type="button" onClick={() => selectCandidate(candidate.id)} className="rounded-xl px-3 py-2 text-sm text-emerald-300">Select</button><button type="button" onClick={() => navigate(`/interviews?candidateId=${candidate.id}&jobId=${candidate.appliedJobId}&action=schedule`)} className="inline-flex items-center gap-1 rounded-xl bg-cyan-500 px-3 py-2 text-sm font-semibold text-slate-950"><CalendarPlus size={15} />Schedule</button><button type="button" onClick={() => setDeleteOpen(true)} className="p-2 text-slate-500 hover:text-rose-300" aria-label="Delete candidate"><Trash2 size={16} /></button></div>} />
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold text-white">Personal details</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{[[Mail, 'Email', candidate.email], [Phone, 'Phone', candidate.phone], [MapPin, 'Location', candidate.location], [MapPin, 'Source', candidate.source], [MapPin, 'Applied', candidate.applicationDate], [MapPin, 'Resume', candidate.resumeFile]].map(([icon, label, value]) => <div key={label}><dt className="flex items-center gap-1 text-xs text-slate-500">{createElement(icon, { size: 12 })}{label}</dt><dd className="mt-1 break-words text-sm text-slate-200">{value || 'Not available'}</dd></div>)}</dl></section><section className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold text-white">Professional profile</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{[['Experience', `${Number(candidate.experienceYears) || 0} years`], ['Education', candidate.education], ['College', candidate.college], ['Graduation year', candidate.graduationYear]].map(([label, value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-sm text-slate-200">{value || 'Not available'}</dd></div>)}</dl>{[['Skills', candidate.skills], ['Certifications', candidate.certifications], ['Projects', candidate.projects]].map(([label, values]) => <div key={label} className="mt-4"><p className="text-xs text-slate-500">{label}</p><div className="mt-2 flex flex-wrap gap-1.5">{values?.length ? values.map((value) => <span key={value} className="rounded-lg bg-white/5 px-2 py-1 text-xs text-slate-300">{value}</span>) : <span className="text-sm text-slate-600">None provided</span>}</div></div>)}</section></div>
    <section className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold text-white">AI match analysis</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{scores.map(([label, score]) => <div key={label} className="rounded-xl bg-white/[0.03] p-3 text-center"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold text-white">{Number(score) || 0}%</p></div>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><p className="text-xs text-emerald-400">Matched skills</p><p className="mt-1 text-sm text-slate-300">{candidate.matchedSkills?.join(', ') || 'None'}</p></div><div><p className="text-xs text-amber-400">Missing skills</p><p className="mt-1 text-sm text-slate-300">{candidate.missingSkills?.join(', ') || 'None'}</p></div><div><p className="text-xs text-slate-500">Strengths</p><p className="mt-1 text-sm text-slate-300">{candidate.strengths?.join(' · ') || 'Not available'}</p></div><div><p className="text-xs text-slate-500">Weaknesses</p><p className="mt-1 text-sm text-slate-300">{candidate.weaknesses?.join(' · ') || 'Not available'}</p></div></div><div className="mt-5 rounded-xl border border-cyan-500/15 bg-cyan-500/5 p-4"><p className="text-sm font-medium text-cyan-300">{candidate.aiRecommendation || 'Manual Review'}</p><p className="mt-1 text-xs text-slate-500">Job threshold: {Number(job?.minimumMatchScore) || 0}% · {Number(candidate.matchScore) >= Number(job?.minimumMatchScore || 0) ? 'Above threshold' : 'Below threshold'}</p></div></section>
    <div className="grid gap-5 xl:grid-cols-2"><CandidateTimeline candidate={candidate} activities={activities} interviews={interviews} /><RecruiterNotes candidate={candidate} onUpdate={(updates) => updateCandidate(candidate.id, updates)} /></div>
    <section className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 className="text-lg font-semibold text-white">Interview history</h2>{history.length ? <div className="mt-4 max-w-full overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-xs text-slate-500"><tr>{['Type', 'Date', 'Interviewer', 'Status', 'Rating', 'Feedback'].map((item) => <th key={item} className="pb-3 font-medium">{item}</th>)}</tr></thead><tbody className="divide-y divide-white/10">{history.map((item) => <tr key={item.id}>{[item.interviewType, `${item.date || '—'} ${item.time || ''}`, item.interviewer, item.status, item.rating ?? '—', item.feedback || '—'].map((value, index) => <td key={index} className="py-3 pr-4 text-slate-400">{value}</td>)}</tr>)}</tbody></table></div> : <p className="py-8 text-center text-sm text-slate-600">No interview history</p>}</section>
    <AddCandidateModal open={editOpen} candidate={candidate} candidates={candidates} jobs={jobs} onClose={() => setEditOpen(false)} onSave={(payload) => updateCandidate(candidate.id, payload)} /><DeleteCandidateModal candidate={deleteOpen ? candidate : null} linkedInterviews={history.length} onClose={() => setDeleteOpen(false)} onDelete={remove} />
  </div>;
};
export default CandidateDetailsPage;
