import { createElement, lazy, Suspense, useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, Clock3, Grid2X2, List, Plus, Star, XCircle } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import CancelInterviewModal from '../components/interviews/CancelInterviewModal';
import FeedbackModal from '../components/interviews/FeedbackModal';
import InterviewCard from '../components/interviews/InterviewCard';
import InterviewDetailsModal from '../components/interviews/InterviewDetailsModal';
import InterviewFilters from '../components/interviews/InterviewFilters';
import InterviewTable from '../components/interviews/InterviewTable';
import InvitationPreviewModal from '../components/interviews/InvitationPreviewModal';
import QuestionGenerator from '../components/interviews/QuestionGenerator';
import ScheduleInterviewModal from '../components/interviews/ScheduleInterviewModal';
import PageHeader from '../components/common/PageHeader';
import RouteLoader from '../components/common/RouteLoader';
import { useRecruitment } from '../context/RecruitmentContext';
import { useToast } from '../context/ToastContext';
import { combineDateAndTime, getTodayISODate, sortInterviewsByDateTime } from '../utils/dateTime';

const InterviewCalendar=lazy(()=>import('../components/interviews/InterviewCalendar'));
const defaults={search:'',status:'',type:'',job:'',interviewer:'',from:'',to:'',rating:'',reminder:'',sort:'upcoming'};
const InterviewsPage=()=>{
  const {interviews,candidates,jobs,activities,loading,scheduleInterview,updateInterview,cancelInterview,submitInterviewFeedback,selectCandidate,rejectCandidate,addActivity}=useRecruitment();
  const {success,error}=useToast(); const [searchParams,setSearchParams]=useSearchParams();
  const queryCandidate=searchParams.get('candidateId'); const validPrefill=searchParams.get('action')==='schedule'&&candidates.some(item=>item.id===queryCandidate);
  const [view,setView]=useState('table'); const [referenceTime]=useState(()=>Date.now()); const [filters,setFilters]=useState(defaults); const [page,setPage]=useState(1);
  const [scheduleState,setScheduleState]=useState(()=>({open:validPrefill,candidateId:validPrefill?queryCandidate:'',date:'',interview:null}));
  const [details,setDetails]=useState(null); const [cancelTarget,setCancelTarget]=useState(null); const [feedbackTarget,setFeedbackTarget]=useState(null); const [questionTarget,setQuestionTarget]=useState(null); const [invitationTarget,setInvitationTarget]=useState(null);
  useEffect(()=>{if(searchParams.get('action')){const next=new URLSearchParams(searchParams);next.delete('action');next.delete('candidateId');next.delete('jobId');setSearchParams(next,{replace:true});}},[searchParams,setSearchParams]);
  const options=useMemo(()=>({jobs,statuses:[...new Set(interviews.map(item=>item.status).filter(Boolean))].sort(),types:[...new Set(interviews.map(item=>item.interviewType).filter(Boolean))].sort(),interviewers:[...new Set(interviews.map(item=>item.interviewer).filter(Boolean))].sort()}),[jobs,interviews]);
  const filtered=useMemo(()=>{const search=filters.search.trim().toLowerCase();let result=interviews.filter(item=>{const text=[item.candidateName,item.jobTitle,item.interviewer,item.interviewType,item.meetingLink].filter(Boolean).join(' ').toLowerCase();return(!search||text.includes(search))&&(!filters.status||item.status===filters.status)&&(!filters.type||item.interviewType===filters.type)&&(!filters.job||item.jobId===filters.job||candidates.find(candidate=>candidate.id===item.candidateId)?.appliedJobId===filters.job)&&(!filters.interviewer||item.interviewer===filters.interviewer)&&(!filters.from||item.date>=filters.from)&&(!filters.to||item.date<=filters.to)&&(!filters.rating||Number(item.rating)>=Number(filters.rating))&&(!filters.reminder||(filters.reminder==='sent'?item.reminderSent:!item.reminderSent));});if(filters.sort==='latest')return sortInterviewsByDateTime(result,'desc');if(filters.sort==='oldest')return sortInterviewsByDateTime(result,'asc');if(filters.sort==='candidate')return result.sort((a,b)=>(a.candidateName||'').localeCompare(b.candidateName||''));if(filters.sort==='rating')return result.sort((a,b)=>Number(b.rating||0)-Number(a.rating||0));if(filters.sort==='status')return result.sort((a,b)=>(a.status||'').localeCompare(b.status||''));const now=referenceTime;return result.sort((a,b)=>{const at=combineDateAndTime(a.date,a.time)?.getTime()??Infinity;const bt=combineDateAndTime(b.date,b.time)?.getTime()??Infinity;const aFuture=at>=now;const bFuture=bt>=now;if(aFuture!==bFuture)return aFuture?-1:1;return aFuture?at-bt:bt-at;});},[interviews,candidates,filters,referenceTime]);
  const metrics=useMemo(()=>{const ratings=interviews.map(item=>Number(item.rating)).filter(value=>value>=1&&value<=5);return[{label:'Total Interviews',value:interviews.length,icon:CalendarDays},{label:'Scheduled',value:interviews.filter(item=>item.status==='Scheduled').length,icon:Clock3},{label:'Completed',value:interviews.filter(item=>item.status==='Completed').length,icon:CheckCircle2},{label:'Cancelled',value:interviews.filter(item=>item.status==='Cancelled').length,icon:XCircle},{label:"Today's Interviews",value:interviews.filter(item=>item.date===getTodayISODate()).length,icon:CalendarDays},{label:'Average Rating',value:ratings.length?(ratings.reduce((sum,value)=>sum+value,0)/ratings.length).toFixed(1):'0.0',icon:Star}];},[interviews]);
  const pageSize=view==='cards'?8:10;const pageCount=Math.max(1,Math.ceil(filtered.length/pageSize));const currentPage=Math.min(page,pageCount);const visible=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize);
  const changeFilter=(name,value)=>{setFilters(current=>({...current,[name]:value}));setPage(1);};const changeView=next=>{setView(next);setPage(1);};
  const candidateFor=interview=>candidates.find(item=>item.id===interview?.candidateId);const jobFor=interview=>jobs.find(item=>item.id===(interview?.jobId||candidateFor(interview)?.appliedJobId));
  const openSchedule=(candidateId='',date='',interview=null)=>setScheduleState({open:true,candidateId,date,interview});
  const saveInterview=payload=>scheduleState.interview?updateInterview(scheduleState.interview.id,{...payload,status:'Rescheduled'}):scheduleInterview(payload);
  const confirmCancel=reason=>{if(cancelInterview(cancelTarget.id,reason)){setCancelTarget(null);}};
  const submitFeedback=values=>submitInterviewFeedback(feedbackTarget.id,values);
  const saveQuestions=questions=>updateInterview(questionTarget.id,{generatedQuestions:questions});
  const invitationSent=result=>{updateInterview(invitationTarget.id,{invitationSent:true,invitationSentAt:result.sentAt});addActivity({type:'interview',title:'Interview invitation sent',description:`Invitation sent to ${invitationTarget.candidateName}.`,relatedId:invitationTarget.id,actor:'Ankit Kumar'});success('Mock invitation sent.','Invitation sent');};
  const copyLink=async interview=>{try{await navigator.clipboard.writeText(interview.meetingLink);success('Meeting link copied.','Copied');}catch{error('Clipboard unavailable.');}};
  const shared={onView:setDetails,onEdit:interview=>openSchedule('', '', interview),onCancel:setCancelTarget,onFeedback:setFeedbackTarget,onCopyLink:copyLink};
  if(loading)return <div className="h-96 animate-pulse rounded-3xl bg-slate-900/70"/>;
  return <div className="min-w-0 space-y-6"><PageHeader eyebrow="Interview coordination" title="Interviews" description="Schedule conversations, prepare panels, and capture structured hiring feedback." actions={<button type="button" onClick={()=>openSchedule()} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2.5 text-sm font-semibold text-slate-950"><Plus size={16}/>Schedule interview</button>}/>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{metrics.map(metric=><article key={metric.label} className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><div className="flex justify-between"><p className="text-xs text-slate-500">{metric.label}</p>{createElement(metric.icon,{size:15,className:'text-cyan-300'})}</div><p className="mt-2 text-2xl font-semibold text-white">{metric.value}</p></article>)}</section>
    <InterviewFilters filters={filters} options={options} onChange={changeFilter} onClear={()=>{setFilters(defaults);setPage(1);}}/><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{filtered.length} interviews</p><div className="flex rounded-xl border border-white/10 p-1">{[['table',List,'Table'],['cards',Grid2X2,'Cards'],['calendar',CalendarDays,'Calendar']].map(([name,icon,label])=><button key={name} type="button" onClick={()=>changeView(name)} className={`inline-flex items-center gap-1 rounded-lg px-3 py-2 text-xs ${view===name?'bg-cyan-500/15 text-cyan-300':'text-slate-500'}`}>{createElement(icon,{size:14})}{label}</button>)}</div></div>
    {!interviews.length?<div className="grid min-h-64 place-items-center text-slate-500">No interviews available</div>:!filtered.length?<div className="grid min-h-64 place-items-center text-slate-500">No interviews match current filters</div>:view==='table'?<InterviewTable interviews={visible}{...shared}/>:view==='cards'?<div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-4">{visible.map(interview=><InterviewCard key={interview.id} interview={interview}{...shared} onQuestions={()=>setQuestionTarget(interview)} onInvitation={()=>setInvitationTarget(interview)} onCopyLink={()=>copyLink(interview)}/>)}</div>:<Suspense fallback={<RouteLoader compact/>}><InterviewCalendar interviews={filtered} onInterview={setDetails} onDay={date=>openSchedule('',date)}/></Suspense>} 
    {view!=='calendar'&&filtered.length>pageSize&&<nav className="flex justify-between"><button type="button" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Previous</button><span className="text-xs text-slate-500">Page {currentPage} of {pageCount}</span><button type="button" disabled={currentPage===pageCount} onClick={()=>setPage(currentPage+1)}>Next</button></nav>}
    <ScheduleInterviewModal open={scheduleState.open} interview={scheduleState.interview} candidates={candidates} jobs={jobs} interviews={interviews} prefillCandidateId={scheduleState.candidateId} prefillDate={scheduleState.date} onClose={()=>setScheduleState({open:false,candidateId:'',date:'',interview:null})} onSave={saveInterview} onInvitation={setInvitationTarget}/>
    <InterviewDetailsModal interview={details} candidate={candidateFor(details)} activities={activities} onClose={()=>setDetails(null)} onEdit={()=>{openSchedule('','',details);setDetails(null);}} onFeedback={()=>{setFeedbackTarget(details);setDetails(null);}} onQuestions={()=>{setQuestionTarget(details);setDetails(null);}} onInvitation={()=>{setInvitationTarget(details);setDetails(null);}}/>
    <CancelInterviewModal interview={cancelTarget} onClose={()=>setCancelTarget(null)} onConfirm={confirmCancel}/><FeedbackModal key={feedbackTarget?.id||'none'} interview={feedbackTarget} candidate={candidateFor(feedbackTarget)} onClose={()=>setFeedbackTarget(null)} onSubmit={submitFeedback} onSelect={()=>selectCandidate(feedbackTarget.candidateId)} onReject={()=>rejectCandidate(feedbackTarget.candidateId)}/>
    <QuestionGenerator key={questionTarget?.id||'none'} interview={questionTarget} candidate={candidateFor(questionTarget)} job={jobFor(questionTarget)} onClose={()=>setQuestionTarget(null)} onSave={saveQuestions}/><InvitationPreviewModal key={invitationTarget?.id||'none'} interview={invitationTarget} candidate={candidateFor(invitationTarget)} onClose={()=>setInvitationTarget(null)} onSent={invitationSent}/>
  </div>;
};
export default InterviewsPage;