export const AUTOMATION_CATEGORIES = ['Candidate Screening', 'Candidate Communication', 'Interview Management', 'Offer Management', 'Reporting', 'Data Synchronization', 'Notifications'];
export const TRIGGER_TYPES = ['Manual', 'Candidate Added', 'Candidate Status Changed', 'Resume Uploaded', 'Interview Scheduled', 'Interview Completed', 'Daily Schedule', 'Weekly Schedule', 'Job Created'];
export const ACTION_TYPES = ['Parse Resume', 'Calculate AI Match Score', 'Shortlist Candidate', 'Reject Candidate', 'Send Email', 'Generate Interview Questions', 'Schedule Interview', 'Send Reminder', 'Update Candidate Status', 'Generate Report', 'Add Activity', 'Create Calendar Event'];

const step = (actionType, label, configuration = {}) => ({ actionType, label, description: '', configuration, continueOnFailure: false, delaySeconds: 0 });
export const automationTemplates = [
  { id: 'TPL-RESUME', name: 'Resume Screening', description: 'Parse a resume and calculate an AI job match.', category: 'Candidate Screening', triggerType: 'Resume Uploaded', estimatedMinutesSavedPerRun: 18, steps: [step('Parse Resume', 'Parse candidate resume'), step('Calculate AI Match Score', 'Calculate job match'), step('Add Activity', 'Record screening result')] },
  { id: 'TPL-SHORTLIST', name: 'Auto Shortlisting', description: 'Shortlist candidates who meet the job threshold.', category: 'Candidate Screening', triggerType: 'Candidate Added', estimatedMinutesSavedPerRun: 12, steps: [step('Calculate AI Match Score', 'Check match threshold'), step('Shortlist Candidate', 'Shortlist qualified candidate')] },
  { id: 'TPL-REJECT', name: 'Candidate Rejection Email', description: 'Send a considerate rejection message.', category: 'Candidate Communication', triggerType: 'Candidate Status Changed', estimatedMinutesSavedPerRun: 8, steps: [step('Send Email', 'Send rejection email', { templateType: 'Rejection' }), step('Add Activity', 'Record candidate communication')] },
  { id: 'TPL-INVITE', name: 'Interview Invitation', description: 'Create a calendar event and send an invitation.', category: 'Interview Management', triggerType: 'Interview Scheduled', estimatedMinutesSavedPerRun: 15, steps: [step('Create Calendar Event', 'Create calendar event'), step('Send Email', 'Send interview invitation', { templateType: 'Interview Invitation' })] },
  { id: 'TPL-REMINDER', name: 'Interview Reminder', description: 'Remind candidates about upcoming interviews.', category: 'Interview Management', triggerType: 'Daily Schedule', estimatedMinutesSavedPerRun: 6, steps: [step('Send Reminder', 'Send interview reminder')] },
  { id: 'TPL-FOLLOWUP', name: 'Post-Interview Follow-up', description: 'Send a follow-up after interview completion.', category: 'Candidate Communication', triggerType: 'Interview Completed', estimatedMinutesSavedPerRun: 8, steps: [step('Send Email', 'Send follow-up email', { templateType: 'Follow-up' }), step('Add Activity', 'Record follow-up')] },
  { id: 'TPL-SELECT', name: 'Candidate Selection Email', description: 'Notify a selected candidate about next steps.', category: 'Offer Management', triggerType: 'Candidate Status Changed', estimatedMinutesSavedPerRun: 10, steps: [step('Send Email', 'Send selection email', { templateType: 'Selection' }), step('Add Activity', 'Record selection communication')] },
  { id: 'TPL-REPORT', name: 'Weekly Recruitment Report', description: 'Generate a weekly recruitment performance summary.', category: 'Reporting', triggerType: 'Weekly Schedule', estimatedMinutesSavedPerRun: 45, steps: [step('Generate Report', 'Build recruitment report'), step('Send Email', 'Share report', { templateType: 'Report' })] },
];

export const cloneTemplate = (template) => JSON.parse(JSON.stringify(template));
